// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text;

if (args.Length > 2)
{
    Console.Error.WriteLine(
        "Usage: dotnet run --file GenerateIconCatalog.cs -- [project-directory] [output-file]");
    return 2;
}

var projectDirectory = Path.GetFullPath(args.Length >= 1
    ? args[0]
    : Directory.GetCurrentDirectory());
var themeDirectory = Path.Combine(projectDirectory, "Win98SE", "SE98");
var outputFile = Path.GetFullPath(args.Length == 2
    ? args[1]
    : Path.Combine(projectDirectory, "Se98Icons.g.cs"));
var resourceFile = Path.Combine(
    Path.GetDirectoryName(outputFile)!,
    "Se98IconResources.g.props");

if (!Directory.Exists(themeDirectory))
{
    Console.Error.WriteLine($"SE98 theme directory not found: {themeDirectory}");
    return 1;
}

var icons = Directory
    .EnumerateFiles(themeDirectory, "*.png", SearchOption.AllDirectories)
    .Where(path => (File.GetAttributes(path) & FileAttributes.ReparsePoint) == 0)
    .Select(path => Path.GetRelativePath(themeDirectory, path).Replace('\\', '/'))
    .Select(path => new Icon(
        path,
        path.Split('/', StringSplitOptions.RemoveEmptyEntries)))
    .Where(icon => icon.Parts.Length == 3)
    .OrderBy(icon => icon.Path, StringComparer.Ordinal)
    .ToArray();

var groupedIcons = icons
    .GroupBy(icon => icon.Parts[0], StringComparer.Ordinal)
    .OrderBy(group => group.Key, StringComparer.Ordinal);
var output = new StringBuilder(
    """
    // SPDX-License-Identifier: GPL-3.0-or-later
    // <auto-generated />
    // Generated by scripts/GenerateIconCatalog.cs. Do not edit manually.

    using Avalonia.Media.Imaging;

    namespace RetroPLC.Icons;

    public static partial class Se98Icons
    {

    """);

foreach (var category in groupedIcons)
{
    output.Append("    public static class ")
        .Append(ToIdentifier(category.Key))
        .AppendLine()
        .AppendLine("    {");

    foreach (var size in category
                 .GroupBy(icon => icon.Parts[1], StringComparer.Ordinal)
                 .OrderBy(group => ParseSize(group.Key))
                 .ThenBy(group => group.Key, StringComparer.Ordinal))
    {
        output.Append("        public static class ")
            .Append(ToIdentifier($"size-{size.Key}"))
            .AppendLine()
            .AppendLine("        {");

        var properties = new HashSet<string>(StringComparer.Ordinal);
        foreach (var icon in size.OrderBy(icon => icon.Path, StringComparer.Ordinal))
        {
            var propertyName = ToIdentifier(Path.GetFileNameWithoutExtension(icon.Parts[2]));
            if (!properties.Add(propertyName))
            {
                throw new InvalidOperationException(
                    $"Icon names collide after C# normalization in " +
                    $"{category.Key}/{size.Key}: {propertyName}");
            }

            output.Append("            public static Bitmap ")
                .Append(propertyName)
                .Append(" => Get(\"")
                .Append(Escape(icon.Path))
                .AppendLine("\");");
        }

        output.AppendLine("        }");
    }

    output.AppendLine("    }");
}

output.AppendLine("}");
Directory.CreateDirectory(Path.GetDirectoryName(outputFile)!);
File.WriteAllText(outputFile, output.ToString(), new UTF8Encoding(false));
var resources = new StringBuilder(
    """
    <!-- SPDX-License-Identifier: GPL-3.0-or-later -->
    <!-- <auto-generated /> -->
    <!-- Generated by scripts/GenerateIconCatalog.cs. Do not edit manually. -->
    <Project>
      <ItemGroup>

    """);
foreach (var icon in icons)
{
    resources.Append("    <AvaloniaResource Include=\"Win98SE/SE98/")
        .Append(EscapeXml(icon.Path))
        .AppendLine("\" />");
}

resources.AppendLine("  </ItemGroup>").AppendLine("</Project>");
File.WriteAllText(resourceFile, resources.ToString(), new UTF8Encoding(false));
Console.WriteLine(
    $"Generated {icons.Length} icon properties and resources in {Path.GetDirectoryName(outputFile)}");
return 0;

static int ParseSize(string value) =>
    int.TryParse(value, out var size) ? size : int.MaxValue;

static string Escape(string value) =>
    value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

static string EscapeXml(string value) =>
    value.Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal);

static string ToIdentifier(string value)
{
    var result = new StringBuilder(value.Length);
    var capitalize = true;
    foreach (var character in value)
    {
        if (!char.IsLetterOrDigit(character))
        {
            capitalize = true;
            continue;
        }

        if (result.Length == 0 && char.IsDigit(character))
            result.Append('_');
        result.Append(capitalize ? char.ToUpperInvariant(character) : character);
        capitalize = false;
    }

    return result.Length == 0 ? "_" : result.ToString();
}

internal sealed record Icon(string Path, string[] Parts);
